### ISSUE TITLE
BUG: Try/Catch para WebSocket Closed.

### ISSUE THREAD

**Issue by jose-compu** [hyperhyperspace/pulsar#24]
WebSocket Not Open Try/Catch:

```
On peer h5GeYJh4fb1bjmiznt4fnyPHOxA=:
Received literal for unknown request 34FFE6EB7544B75457939574493B1374
Error
    at Logger.log (/home/ec2-user/workspace/@hyper-hyper-space/core/dist/util/logging.js:41:27)
    at Logger.warning (/home/ec2-user/workspace/@hyper-hyper-space/core/dist/util/logging.js:25:30)
    at HistorySynchronizer.onReceivingLiteral (/home/ec2-user/workspace/@hyper-hyper-space/core/dist/mesh/agents/state/history/HistorySynchronizer.js:426:32)
    at HeaderBasedSyncAgent.receivePeerMessage (/home/ec2-user/workspace/@hyper-hyper-space/core/dist/mesh/agents/state/HeaderBasedSyncAgent.js:86:31)
    at PeerGroupAgent.onPeerMessage (/home/ec2-user/workspace/@hyper-hyper-space/core/dist/mesh/agents/peer/PeerGroupAgent.js:616:30)
    at PeerGroupAgent.receiveLocalEvent (/home/ec2-user/workspace/@hyper-hyper-space/core/dist/mesh/agents/peer/PeerGroupAgent.js:691:22)
    at SecureNetworkAgent.receiveMessage (/home

**Comment by sbazerque** [comment]
I'm trying to find the rest of the log entry to recover the actual message, but haven't found it so far
