### ISSUE TITLE
Failed to set remote description, reason: {}

### ISSUE THREAD

**Issue by joigno** [hyperhyperspace/pulsar#25]
With testnet1 (`yarn start --network="eyesight print detail"`):

```
[BlockOp 15:30 4.872]: Received #269 with steps=106 and timestamp=8/29/2021, 3:29:02 PM by qWY63VG6TaSiOMFXFOijmV5U6Gs=, block time 82.4550s, block hash ends in 89YaU=
[BlockOp 15:30 4.872]: Tokenomics: movingMaxSpeed=150.0000, movingMinSpeed=44.1440, blockTimeFactor=103.0998, speedRatio=3.3980, currentSpeed=1.2855
[BlockOp 15:30 4.988]: Received #270 with steps=112 and timestamp=8/29/2021, 3:29:31 PM by rRrKzWRNow+NseobNT3pzAkgoP0=, block time 29.5470s, block hash ends in VJOxg=
[BlockOp 15:30 4.988]: Tokenomics: movingMaxSpeed=150.0000, movingMinSpeed=44.1236, blockTimeFactor=103.1475, speedRatio=3.3995, currentSpeed=3.7906
[Blockchain 15:30 5.044]: Mining #271, got 4304 steps for challenge ending in a3da33...
[WebRTCConnection 15:30 5.047]: Failed to set remote description, reason: {}
Error
    at Logger.log (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/util/logging.js:41:27)
    at Logger.warning (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/util/logging.js:25:30)
    at /Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/net/transport/WebRTCConnection.js:208:41
[WebRTCConnection 15:30 5.049]: Failed to set remote description, reason: {}
Error
    at Logger.log (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/util/logging.js:41:27)
    at Logger.warning (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/util/logging.js:25:30)
    at /Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/net/transport/WebRTCConnection.js:208:41
[BlockOp 15:30 14.588]: Received #270 with steps=108 and timestamp=8/29/2021, 3:30:13 PM by Cq2MUGYjJaeFUjF+nnGLy6veUDs=, block time 71.1650s, block hash ends in bvO78=
[BlockOp 15:30 14.588]: Tokenomics: movingMaxSpeed=150.0000, movingMinSpeed=44.1236, blockTimeFactor=103.0520, speedRatio=3.3995, currentSpeed=1.5176
[Blockchain 15:30 14.635]: Mining #271, got 110 steps for challenge ending in 85de10...
```

**Comment by sbazerque** [comment]
I _think_ this an issue with the library that implements WebRTC outside of the browser. I'll just catch the error and let the automatic re-connection happen. It'd be wise to use the transport websocket when runnig on the server side, but that's a task for another day :)

**Comment by joigno** [comment]
excellent

**Comment by sbazerque** [comment]
There is already a catch for this, the log message is just a warning about the remote description not being set:

> this.connection.setRemoteDescription(description).catch((reason: any) => {
>                 WebRTCConnection.logger.warning('Failed to set remote description, reason: ' + JSON.stringify(reason));
> });

@joigno , was there really a fork after this message was shown? Because the log seems to show progress after it, but I'm unsure.
