### ISSUE TITLE
HistorySyncronizer error -> "status is not `sent`"

### ISSUE THREAD

**Issue by joigno** [hyperhyperspace/pulsar#26]
```
[HistorySynchronizer 12:13 34.848]:
On peer GVmsXCdsww2DSJXSDaJKxcdbQ20=:
Ignoring response for request 4475DF5E597995BCDB9FC188DD4DC1F8: status is not 'sent'
Error
    at Logger.log (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/util/logging.js:41:27)
    at Logger.warning (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/util/logging.js:25:30)
    at HistorySynchronizer.onReceivingResponse (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/state/history/HistorySynchronizer.js:389:29)
    at HeaderBasedSyncAgent.receivePeerMessage (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/state/HeaderBasedSyncAgent.js:83:31)
    at PeerGroupAgent.onPeerMessage (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/peer/PeerGroupAgent.js:616:30)
    at PeerGroupAgent.receiveLocalEvent (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/peer/PeerGroupAgent.js:691:22)
    at SecureNetworkAgent.receiveMessage (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/network/SecureNetworkAgent.js:386:35)
    at SecureNetworkAgent.receiveLocalEvent (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/network/SecureNetworkAgent.js:181:18)
    at NetworkAgent.receiveMessage (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/network/NetworkAgent.js:523:19)
    at WebRTCConnection.NetworkAgent.messageCallback (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/network/NetworkAgent.js:62:34)
```

**Comment by sbazerque** [comment]
Adding a bit of context:

```
[HistorySynchronizer 12:13 34.848]:
On peer GVmsXCdsww2DSJXSDaJKxcdbQ20=:
Ignoring response for request 4475DF5E597995BCDB9FC188DD4DC1F8: status is not 'sent'
Error
    at Logger.log (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/util/logging.js:41:27)
    at Logger.warning (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/util/logging.js:25:30)
    at HistorySynchronizer.onReceivingResponse (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/state/history/HistorySynchronizer.js:389:29)
    at HeaderBasedSyncAgent.receivePeerMessage (/Users/jose/Documents/GitHub/workspace/@hyper-hyper-space/core/dist/mesh/agents/state/HeaderBasedSyncAgent.js:83:31)
```

**Comment by sbazerque** [comment]
OK - this appens when we receive a response we were not expecting, but I need a bit more info to know why this is happened. Committing a more verbose logger for this problem now.
